---
extends: default
rules:
  line-length:
    max: 140
    level: warning
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 1
ignore: |
  .github/workflows/
  .ansible/
  .venv/
  k8s/**/charts/
  itential/docker-compose.yml
