"""PID S4d element 3 (ADR 0043/0044): the Lifecycle Manager model branch-vlan (itential/lcm/), the JSON form on
the approval task (itential/forms/, generated by itential/forms/build.py), the create/delete action workflows
(itential/workflows/build.py) and ansible/playbooks/tasks/lcm.yml. These tests hold the documents, the oracle,
the generators, the play, the verify scripts and the PID to each other. They run in CI with no lab access."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parent.parent
VERSIONS = ROOT / "itential" / "versions.yaml"
LCM = ROOT / "itential" / "lcm"
FORMS = ROOT / "itential" / "forms"
WORKFLOWS = ROOT / "itential" / "workflows"
PLAY = ROOT / "ansible" / "playbooks" / "platform.yml"
TASKS = ROOT / "ansible" / "playbooks" / "tasks" / "lcm.yml"
VERIFY = ROOT / "verify" / "test-06b-platform.sh"
VERIFY_05 = ROOT / "verify" / "test-05-itential.sh"
VERIFY_06 = ROOT / "verify" / "test-06-flowai.sh"
PID = ROOT / "docs" / "PID.md"
ADRS = ROOT / "docs" / "adr"

FORM_VIEW = "/json-forms/task/ShowJsonForm"  # measured on 6.5.2: app JsonForms, incoming form_id + instance_data, outgoing export
APPROVAL_FIELDS = {"branch", "vid", "vlan_name", "switch", "netbox_vlan_id"}  # PID S4d.3: branch, VLAN, switch, NetBox reservation


@pytest.fixture(scope="module")
def versions() -> dict:
    return yaml.safe_load(VERSIONS.read_text())


@pytest.fixture(scope="module")
def lcm(versions: dict) -> dict:
    assert "lcm" in versions and "forms" in versions, "itential/versions.yaml needs lcm and forms sections (ADR 0043/0044)"
    return versions["lcm"]


@pytest.fixture(scope="module")
def model(lcm: dict) -> dict:
    return yaml.safe_load((LCM / f"{lcm['model']}.yaml").read_text())


@pytest.fixture(scope="module")
def form(versions: dict) -> dict:
    return json.loads((FORMS / f"{versions['forms']['approval']}.json").read_text())


def test_oracle_names_the_model_its_workflows_and_the_form(versions: dict, lcm: dict) -> None:
    wf = versions["workflows"]
    assert lcm["model"] == "branch-vlan"
    assert lcm["actions"] == {"create": wf["branch_vlan"], "delete": wf["branch_vlan_delete"]}
    assert wf["branch_vlan_delete"] == "Remove Branch VLAN"
    assert lcm["instance_name"] == "<branch>-<vlan_name>", "instance names are known before the run (the VID is chosen inside it)"
    assert set(lcm["netbox_vlan_groups"]) == {"br1-user", "br2-user"}, "the branch VLAN groups itential.yml creates"
    assert versions["forms"]["approval"].startswith("lab-") and versions["forms"]["documents"] == "itential/forms"
    assert lcm["documents"] == "itential/lcm"


def test_model_document_schema_and_actions(lcm: dict, model: dict) -> None:
    assert model["name"] == lcm["model"]
    schema = model["schema"]
    assert schema["type"] == "object" and schema["additionalProperties"] is False
    assert set(schema["required"]) == APPROVAL_FIELDS | {"status"}, "every field the workflows publish as the instance"
    assert schema["properties"]["vid"]["type"] == "integer" and schema["properties"]["netbox_vlan_id"]["type"] == "integer"
    assert set(schema["properties"]["branch"]["enum"]) == {"br1", "br2"}
    assert set(schema["properties"]["status"]["enum"]) >= {"reserved", "active", "deleted"}
    actions = {a["type"]: a for a in model["actions"]}
    assert set(actions) == {"create", "delete"}, "update is not a lab use case; import is done by the play"
    for a in model["actions"]:
        assert re.fullmatch(r"[0-9a-f]{4}", a["_id"]), "LCM action ids are 4-hex like task ids"
        assert a["preWorkflowJst"] is None and a["postWorkflowJst"] is None, "no transformations: the workflows publish `instance` themselves"
        assert a["workflow"] == lcm["actions"][a["type"]], "actions reference workflows by NAME: the name survives the itential.yml re-import (measured)"


def test_form_generated_from_build_py_and_shaped_for_the_approval(versions: dict, form: dict) -> None:
    build = FORMS / "build.py"
    assert build.exists(), "itential/forms/build.py generates the form documents"
    out = subprocess.run([sys.executable, str(build), "--check"], capture_output=True, text=True, cwd=ROOT, check=False)
    assert out.returncode == 0, f"itential/forms/*.json differ from build.py: {out.stdout}{out.stderr}"
    assert form["name"] == versions["forms"]["approval"]
    assert form["struct"]["type"] == "array", "a struct of type object renders empty (builder skill, confirmed)"
    keys = [i["customKey"] for i in form["struct"]["items"]]
    assert set(keys) == set(form["schema"]["properties"]), "struct items and schema properties must stay in sync"
    assert APPROVAL_FIELDS <= set(keys) and "decision" in keys
    for item in form["struct"]["items"]:
        if item["customKey"] != "decision":
            assert item["readOnly"] is True, f"{item['customKey']}: the approver reads the context, the workflow wrote it"
            assert form["uiSchema"][item["customKey"]].get("ui:readonly") is True
    decision = next(i for i in form["struct"]["items"] if i["customKey"] == "decision")
    assert [e["value"] for e in decision["enum"]] == ["approve", "reject"]
    assert form["schema"]["properties"]["decision"]["enum"] == ["approve", "reject"]
    assert form["schema"]["properties"]["decision"]["default"] == "reject", "an untouched form rejects; nothing is pushed by accident"
    assert form["schema"]["required"] == ["decision"]
    assert form["bindingSchema"] == {} and form["validationSchema"] == {}


def test_create_workflow_approves_on_the_form_and_publishes_the_instance(versions: dict) -> None:
    wf = json.loads((WORKFLOWS / "add-branch-vlan.json").read_text())
    tasks, tr = wf["tasks"], wf["transitions"]
    manual = [k for k, t in tasks.items() if t.get("type") == "manual"]
    assert len(manual) == 1, "exactly one approval"
    approval = tasks[manual[0]]
    assert approval["name"] == "ShowJsonForm" and approval["app"] == "JsonForms" and approval["view"] == FORM_VIEW
    assert approval["variables"]["incoming"]["form_id"] == versions["forms"]["approval"], "the form by its stable name"
    assert approval["variables"]["incoming"]["instance_data"].startswith("$var."), "defaults from a top-level $var object (a literal would not resolve)"
    assert approval["variables"]["outgoing"]["export"] == "$var.job.approval"
    assert not any(t.get("name") == "ViewData" for t in tasks.values()), "the ViewData approval is replaced (ADR 0044)"
    # the decision gate: success -> evaluation of export.decision == approve; anything else rolls the reservation back
    nxt = {k for k, e in tr[manual[0]].items() if e["state"] == "success"}
    assert len(nxt) == 1
    gate = tasks[nxt.pop()]
    ev = gate["variables"]["incoming"]["evaluation_groups"][0]["evaluations"][0]
    assert gate["name"] == "evaluation" and ev["query"] == "decision" and ev["operand_2"]["variable"] == "approve" and ev["operator"] == "=="
    # S4f (ADR 0054): the NetBox delete is the integration's operation now, not the adapter's method.
    rollback = [k for k, t in tasks.items() if t.get("name") == "ipam_vlans_destroy"]
    assert len(rollback) == 1
    gate_id = next(k for k, t in tasks.items() if t is gate)
    assert tr[gate_id].get(rollback[0], {}).get("state") == "failure"
    assert tr[manual[0]].get(rollback[0], {}).get("state") == "failure", "a failure finish (API) rolls back like a reject"
    # the LCM create action stores $var.job.instance: published on the applied path and on the no-op path
    writers = [k for k, t in tasks.items() if t.get("variables", {}).get("outgoing", {}).get("textObject") == "$var.job.instance"]
    assert len(writers) == 2, f"instance published on both paths, found {writers}"
    assert wf["outputSchema"]["properties"]["instance"]["type"] == "object"
    assert set(wf["inputSchema"]["required"]) == {"branch", "vlan_name"}, "inputs unchanged: S4.4, S4b and S4c.3 keep working"


def test_delete_workflow_writes_to_the_device_only_through_the_governed_push(versions: dict) -> None:
    wf = json.loads((WORKFLOWS / "remove-branch-vlan.json").read_text())
    tasks = wf["tasks"]
    assert wf["inputSchema"]["properties"]["instance"]["type"] == "object", "LCM passes the instance data as the job variable `instance`"
    assert "instance" not in wf["inputSchema"]["required"], "LCM injects it; a direct start may pass it"
    assert not any(t.get("name") in ("sendConfig", "ViewData") for t in tasks.values()), "no direct device write, no second approval"
    child = [t for t in tasks.values() if t.get("name") == "childJob"]
    assert len(child) == 1 and child[0]["variables"]["incoming"]["workflow"] == versions["workflows"]["config_push"]
    cfg = child[0]["variables"]["incoming"]["variables"]["config"]
    src = tasks[cfg["task"]]["variables"]["incoming"]
    assert "no vlan " in json.dumps(src), "the push is exactly `no vlan <vid>`"
    assert any(t.get("name") == "ipam_vlans_destroy" for t in tasks.values()), "the NetBox VLAN goes too"
    show = [t for t in tasks.values() if t.get("name") == "sendCommand"]
    assert show and "show vlan" in json.dumps([t.get("variables", {}).get("incoming") for t in tasks.values()]), \
        "the switch is read before it is written: `no vlan` is pushed only when the VLAN exists (no-op when absent)"
    assert any(t.get("variables", {}).get("outgoing", {}).get("textObject") == "$var.job.instance" for t in tasks.values())
    assert wf["outputSchema"]["properties"]["changed"]["type"] == "boolean"


def test_play_creates_form_model_and_instances_through_the_api(lcm: dict) -> None:
    assert TASKS.exists() and "tasks/lcm.yml" in PLAY.read_text()
    text = TASKS.read_text()
    for s in ("json-forms/forms", "lifecycle-manager/resources", "actions/validate", "instances/import", "ipam/vlans", "lcm.netbox_vlan_groups"):
        assert s in text, f"tasks/lcm.yml lacks {s}"
    for bad in ("run-action", "sendConfig", "gateway_manager"):
        assert bad not in text, f"the play only declares objects; {bad} does not belong here"


def test_verify_scripts_pid_and_adrs_cover_s4d3(versions: dict) -> None:
    text = VERIFY.read_text()
    assert re.search(r'check "S4d\.3 ', text) and "DEFER S4d.3" not in text and "S4d.3 Lifecycle Manager + JSON Forms (element 3, not built yet)" not in text
    for s in ("run-action", "work-center-service/work-items", "variables/incoming", "action-executions", "devcmd.py"):
        assert s in text, f"verify 06b S4d.3 lacks {s}"
    for path in (VERIFY_05, VERIFY_06, VERIFY):
        assert '"export"' in path.read_text() or "export" in path.read_text(), f"{path.name}: the form approval carries export.decision"
    assert re.search(r'decision[^\n]*approve', VERIFY_05.read_text()) and re.search(r'decision[^\n]*approve', VERIFY_06.read_text())
    pid = PID.read_text()
    assert "| 1.9 |" in pid and "Remove Branch VLAN" in pid
    assert list(ADRS.glob("0043-*.md")) and list(ADRS.glob("0044-*.md"))


def test_every_generated_workflow_uses_hex_task_ids_and_reaches_its_end() -> None:
    """The import rejects a task id outside ^[0-9a-f]{1,4}$ (measured: '1g' failed the whole import) and a task
    without a path from workflow_start fails the job at start; both are cheap to hold here."""
    for path in sorted(WORKFLOWS.glob("*.json")):
        wf = json.loads(path.read_text())
        tasks, tr = wf["tasks"], wf["transitions"]
        bad = [k for k in tasks if k not in ("workflow_start", "workflow_end") and not re.fullmatch(r"[0-9a-f]{1,4}", k)]
        assert not bad, f"{path.name}: task ids must be 1-4 hex digits: {bad}"
        seen, stack = set(), ["workflow_start"]
        while stack:
            a = stack.pop()
            if a in seen:
                continue
            seen.add(a)
            stack += list(tr.get(a, {}))
        assert set(tasks) <= seen, f"{path.name}: unreachable tasks {sorted(set(tasks) - seen)}"
        assert not {b for a in tr for b in tr[a] if b not in tasks}, f"{path.name}: transition to a missing task"
