"""PID S4d element 4 (ADR 0045): Integration Models for NetBox and the ServiceNow PDI, generated by
itential/integrations/build.py from a short operation list, created and started by ansible/playbooks/tasks/integrations.yml
and registered as agent tools. These tests hold the oracle, the generator, the documents, the play, the agents, the verify
scripts and the PID to each other. They run in CI with no lab access."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parent.parent
VERSIONS = ROOT / "itential" / "versions.yaml"
DOCS = ROOT / "itential" / "integrations"
AGENTS = ROOT / "itential" / "agents"
PLAY = ROOT / "ansible" / "playbooks" / "platform.yml"
TASKS = ROOT / "ansible" / "playbooks" / "tasks" / "integrations.yml"
AGENT_TASK = ROOT / "ansible" / "playbooks" / "tasks" / "flowai-agent.yml"
VERIFY = ROOT / "verify" / "test-06b-platform.sh"
PID = ROOT / "docs" / "PID.md"
ADRS = ROOT / "docs" / "adr"


@pytest.fixture(scope="module")
def versions() -> dict:
    return yaml.safe_load(VERSIONS.read_text())


@pytest.fixture(scope="module")
def integrations(versions: dict) -> dict:
    assert "integrations" in versions, "itential/versions.yaml needs an integrations section (ADR 0045)"
    return versions["integrations"]


@pytest.fixture(scope="module")
def docs(integrations: dict) -> dict:
    return {k: json.loads((DOCS / f"{m['title']}.json").read_text()) for k, m in integrations["models"].items()}


def test_oracle_names_both_models_and_their_instances(integrations: dict) -> None:
    models = integrations["models"]
    assert set(models) == {"netbox", "servicenow"}
    for key, m in models.items():
        assert m["title"].startswith("lab-") and re.fullmatch(r"\d+\.\d+\.\d+", str(m["version"])), m
        assert m["instance"].endswith("-api"), "the integration is named apart from the adapter instances NetBox / ServiceNow"
        assert m["auth"] and m["server"]["protocol"] in ("http", "https")
    assert "host" not in models["servicenow"]["server"], "the PDI host comes from SNOW_INSTANCE in .env"
    assert integrations["documents"] == "itential/integrations"


def test_documents_generated_and_scoped(integrations: dict, docs: dict) -> None:
    build = DOCS / "build.py"
    out = subprocess.run([sys.executable, str(build), "--check"], capture_output=True, text=True, cwd=ROOT, check=False)
    assert out.returncode == 0, f"itential/integrations/*.json differ from build.py: {out.stdout}{out.stderr}"
    for key, doc in docs.items():
        m = integrations["models"][key]
        assert doc["openapi"].startswith("3.") and doc["info"]["title"] == m["title"] and doc["info"]["version"] == str(m["version"])
        assert m["auth"] in doc["components"]["securitySchemes"], "the auth scheme the play fills is declared"
        ops = [(p, verb, o["operationId"]) for p, item in doc["paths"].items() for verb, o in item.items()]
        assert ops and all(o[2] for o in ops)
        assert len(ops) <= 12, f"{key}: an agent tool set stays small ({len(ops)} operations)"
        for p, verb, oid in ops:
            o = doc["paths"][p][verb]
            assert o["security"] == [{m["auth"]: []}], f"{oid}: every operation is secured by the model's scheme"
            assert "200" in o["responses"]
    nb_ops = {verb for item in docs["netbox"]["paths"].values() for verb in item}
    assert nb_ops == {"get"}, "NetBox through the integration is read-only: writes go through the adapter in workflows"
    sn = docs["servicenow"]["paths"]
    assert "get" in sn["/api/now/table/incident"] and "get" in sn["/api/now/table/incident/{sys_id}"]
    assert set(sn["/api/now/table/incident/{sys_id}"]) <= {"get", "patch"}, "the only ServiceNow write is an incident update (work notes)"
    assert docs["servicenow"]["servers"][0]["url"].startswith("https://example."), "no PDI host in the document"


def test_play_creates_validates_starts_and_registers(integrations: dict) -> None:
    assert TASKS.exists() and "tasks/integrations.yml" in PLAY.read_text()
    text = TASKS.read_text()
    for s in ("integration-models/validation", "integration-models", "/integrations", "/start", "tools/discover", "SNOW_INSTANCE", "SNOW_USER", "NETBOX_TOKEN"):
        assert s in text, f"tasks/integrations.yml lacks {s}"
    assert "no_log: true" in text, "credentials never logged"


def test_agent_tool_kind_integration_resolves_in_the_registry() -> None:
    text = AGENT_TASK.read_text()
    assert "integration" in text, "tasks/flowai-agent.yml resolves kind: integration tools"
    used = [p for p in AGENTS.glob("*.yaml") if any(t.get("kind") == "integration" for t in yaml.safe_load(p.read_text())["tools"])]
    assert used, "at least one agent document uses an integration tool"


def test_verify_pid_and_adr_cover_s4d4() -> None:
    text = VERIFY.read_text()
    assert re.search(r'check "S4d\.4 ', text) and "S4d.4 Integration Models (element 4, not built yet)" not in text
    for s in ("integration-models", "TOOL_CALLED", "service-now.com", "dcim/devices"):
        assert s in text, f"verify 06b S4d.4 lacks {s}"
    pid = PID.read_text()
    assert "| 1.10 |" in pid and "lab-netbox" in pid
    assert list(ADRS.glob("0045-*.md"))
