#!/usr/bin/env python3
"""Generate the BGP session rules (R10) from topology/enterprise.yaml through topology/derive.py, the intent NetBox's
config contexts are seeded from (ADR 0048). One PrometheusRule, group lab-bgp:

  lab:bgp_neighbor_intent      1 per declared session end: device, neighbor, vrf ("default" outside a VRF), the peer
                               device that owns the neighbor address, its remote_as, and the device pair (`pair`, the
                               two names sorted): both ends of a broken session alert at once (probe P3), and
                               Alertmanager groups them by pair so the outage loop is started once (R10 PR B)
  lab:bgp_session_up:snmp      1/0 per C8000v session, BGP4-MIB bgpPeerState (6 = established) - every VRF (probe P1)
  lab:bgp_session_up:gnmic     1/0 per vEOS session from gNMIc's session-state series
  lab:bgp_session_up           either source, for declared sessions only, with the intent's labels
  LabBgpSessionDown            lab:bgp_session_up == 0 for 2 m

gNMIc keeps the previous state's series until its 2 m expiry (observability/gnmic/gnmic.yaml.j2), so on every
transition an ESTABLISHED and a non-ESTABLISHED series both read 1 (probe P3, 2026-10-05). An ESTABLISHED series wins:
the down side then waits ~1.5 m for the stale ESTABLISHED one to expire, but a 1-2 s BFD flap - the leaf <-> WAN edge
sessions have dozens a day - never reads as 2 m down, and a recovered session reads up at once.

  python observability/bgp_rules.py           write k8s/observability/manifests/bgp-rules.yaml
  python observability/bgp_rules.py --check   exit 1 when the committed file differs (tests/test_bgp_rules.py)
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "k8s" / "observability" / "manifests" / "bgp-rules.yaml"
HEADER = "# Generated by observability/bgp_rules.py from topology/enterprise.yaml (R10) - do not edit by hand.\n"
_SPEC = importlib.util.spec_from_file_location("derive", ROOT / "topology" / "derive.py")
derive = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(derive)

# the topology platform -> the source that reports its sessions (owner decision 2026-10-05)
SOURCES = {"veos": "gnmic", "c8000v": "snmp"}
GNMIC = '{__name__=~"gnmic_bgp.*session_state", session_state%s"ESTABLISHED"}'


def _gnmic_by_session(match: str) -> str:
    renamed = (f'label_replace(label_replace({GNMIC % match}, "device", "$1", "source", "(.*)"), '
               '"neighbor", "$1", "neighbor_neighbor_address", "(.*)")')
    return f"max by (device, neighbor) ({renamed})"


def intent() -> list[dict]:
    """Every declared session end, with the device that owns the neighbor address as its peer."""
    topo = derive.load_topology()
    owner = {row["address"].split("/")[0]: device
             for device, rows in derive.interfaces(topo).items() for row in rows if row.get("address")}
    ends = []
    for device in topo["nodes"]:
        for n in derive.device_context(topo, device).get("bgp", {}).get("neighbors", []):
            peer = owner[n["neighbor"]]
            ends.append({"device": device, "neighbor": n["neighbor"], "vrf": n.get("vrf") or "default",
                         "peer": peer, "remote_as": str(n["remote_as"]), "pair": "--".join(sorted((device, peer)))})
    return ends


def build(ends: list[dict]) -> dict:
    rules: list[dict] = [{"record": "lab:bgp_neighbor_intent", "expr": "vector(1)", "labels": e} for e in ends]
    rules += [
        {
            "record": "lab:bgp_session_up:snmp",
            "expr": 'max by (device, neighbor) (label_replace(bgpPeerState{job="snmp-ios-xe"}, "neighbor", "$1", '
                    '"bgpPeerRemoteAddr", "(.*)") == bool 6)',
        },
        {
            "record": "lab:bgp_session_up:gnmic",
            "expr": f"{_gnmic_by_session('=')} or 0 * {_gnmic_by_session('!=')}",
        },
        {
            "record": "lab:bgp_session_up",
            "expr": "(lab:bgp_session_up:snmp or lab:bgp_session_up:gnmic) "
                    "* on (device, neighbor) group_left (vrf, peer, remote_as, pair) lab:bgp_neighbor_intent",
        },
        {
            "alert": "LabBgpSessionDown",
            "expr": "lab:bgp_session_up == 0",
            "for": "2m",
            "labels": {"severity": "warning"},
            "annotations": {
                "summary": "BGP session {{ $labels.device }} -> {{ $labels.neighbor }} ({{ $labels.peer }}, "
                           "VRF {{ $labels.vrf }}) is not Established",
                "description": "Not Established for 2 minutes (SNMP BGP4-MIB on IOS-XE, gNMIc on vEOS); "
                               "declared in topology/enterprise.yaml.",
            },
        },
    ]
    return {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {"name": "lab-bgp", "namespace": "observability", "labels": {"role": "lab-alert-rules"}},
        "spec": {"groups": [{"name": "lab-bgp", "rules": rules}]},
    }


class _Dumper(yaml.SafeDumper):
    def increase_indent(self, flow: bool = False, indentless: bool = False):  # sequences indented under their key
        return super().increase_indent(flow, False)


def render(ends: list[dict]) -> str:
    return HEADER + yaml.dump(build(ends), Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=200)


def main(argv: list[str]) -> int:
    text = render(intent())
    if "--check" in argv:
        if OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} differs from what the topology renders: run observability/bgp_rules.py")
            return 1
        return 0
    OUT.write_text(text)
    print(OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
