#!/usr/bin/env python3
"""Generate the expiry rules (ADR 0071) from observability/expiries.yaml: one PrometheusRule with a days-left series
per entry (`lab:expiry_days_left`, the date taken as 00:00 UTC) and one alert, LabExpirySoon, under warn_days. Plain
arithmetic on time(), so no exporter runs; the Expiries dashboard reads the series.

  python observability/expiry_rules.py           write k8s/observability/manifests/expiry-rules.yaml
  python observability/expiry_rules.py --check   exit 1 when the committed file differs (tests/test_expiry_rules.py)
"""

from __future__ import annotations

import datetime
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "observability" / "expiries.yaml"
OUT = ROOT / "k8s" / "observability" / "manifests" / "expiry-rules.yaml"
HEADER = (
    "# Generated by observability/expiry_rules.py from observability/expiries.yaml (ADR 0071) - do not edit by hand.\n"
)


def _epoch(day: str) -> int:
    return int(datetime.datetime.fromisoformat(day + "T00:00:00+00:00").timestamp())


def build(doc: dict) -> dict:
    warn = int(doc["warn_days"])
    rules: list[dict] = [
        {
            "record": "lab:expiry_days_left",
            "expr": f"({_epoch(e['expires'])} - time()) / 86400",
            "labels": {"key": e["key"], "name": e["name"], "expires": e["expires"]},
        }
        for e in doc["expiries"]
    ]
    rules.append(
        {
            "alert": "LabExpirySoon",
            "expr": f"lab:expiry_days_left < {warn}",
            "for": "1h",
            "labels": {"severity": "warning"},
            "annotations": {
                "summary": "{{ $labels.name }} expires on {{ $labels.expires }}",
                "description": "{{ $value | humanize }} days left (observability/expiries.yaml, warning under "
                + str(warn)
                + " days).",
            },
        }
    )
    return {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {"name": "lab-expiries", "namespace": "observability", "labels": {"role": "lab-alert-rules"}},
        "spec": {"groups": [{"name": "lab-expiries", "interval": "1h", "rules": rules}]},
    }


class _Dumper(yaml.SafeDumper):
    def increase_indent(self, flow: bool = False, indentless: bool = False):  # sequences indented under their key
        return super().increase_indent(flow, False)


def render(doc: dict) -> str:
    return HEADER + yaml.dump(build(doc), Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=200)


def main(argv: list[str]) -> int:
    text = render(yaml.safe_load(SOURCE.read_text()))
    if "--check" in argv:
        if OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} differs from what expiries.yaml renders: run observability/expiry_rules.py")
            return 1
        return 0
    OUT.write_text(text)
    print(OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
