#!/usr/bin/env python3
"""Generate the two data-driven Zabbix templates (ADR 0051 decision 5) in the 7.0 export format:

  templates/lab-expiries.yaml  one Script item per entry of observability/expiries.yaml (days left, computed
                               in the item's JavaScript from the date), trigger under warn_days
  templates/lab-web-ui.yaml    one HTTP agent item per observability.yaml web_check (HTTP status from the
                               response headers), trigger when not the expected status

  python observability/zabbix/build.py           write both files
  python observability/zabbix/build.py --check   exit 1 when a committed file differs (tests/test_observability.py)

UUIDs are derived from the key (uuid5, shaped as v4 for Zabbix's validator), so the output is stable.
"""

from __future__ import annotations

import sys
import uuid
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "templates"
GROUP = "Templates/Lab"
NS = uuid.UUID("6b1f7d1e-0c2a-4d3e-9a7f-2f2c1e8d5a01")  # namespace for the lab's deterministic UUIDs


def uid(*parts: str) -> str:
    h = uuid.uuid5(NS, "/".join(parts)).hex
    return h[:12] + "4" + h[13:16] + "8" + h[17:]


def _dump(doc: dict) -> str:
    class Dumper(yaml.SafeDumper):
        def increase_indent(self, flow=False, indentless=False):  # yamllint-style: sequences indented under their key
            return super().increase_indent(flow, False)

    def str_rep(dumper, data):  # quote strings that look like other scalars
        style = "'" if data in ("YES", "NO") or data.replace(".", "").isdigit() else None
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)

    Dumper.add_representer(str, str_rep)
    return yaml.dump(doc, Dumper=Dumper, sort_keys=False, allow_unicode=True, width=200)


def expiries() -> dict:
    doc = yaml.safe_load((ROOT / "observability" / "expiries.yaml").read_text())
    warn = int(doc["warn_days"])
    items = []
    for e in doc["expiries"]:
        key = f"expiry.days[{e['key']}]"
        items.append(
            {
                "uuid": uid("item", key),
                "name": f"Days until: {e['name']}",
                "type": "SCRIPT",
                "key": key,
                "delay": "1h",
                "value_type": "FLOAT",
                "units": "d",
                "params": "var p = JSON.parse(value);\nreturn ((new Date(p.expires + 'T00:00:00Z') - Date.now()) / 86400000).toFixed(2);",
                "parameters": [{"name": "expires", "value": e["expires"]}],
                "description": f"Source: {e['source']}. Expires {e['expires']}.",
                "tags": [{"tag": "component", "value": "expiry"}, {"tag": "expiry", "value": e["key"]}],
                "triggers": [
                    {
                        "uuid": uid("trigger", key),
                        "expression": f"last(/lab-expiries/{key})<{warn}",
                        "name": f"LAB: {e['name']} expires in {{ITEM.LASTVALUE1}} days",
                        "priority": "HIGH",
                        "description": f"Under {warn} days left (observability/expiries.yaml).",
                        "manual_close": "YES",
                        "tags": [{"tag": "scope", "value": "expiry"}],
                    }
                ],
            }
        )
    return {
        "zabbix_export": {
            "version": "7.0",
            "template_groups": [{"uuid": uid("group", GROUP), "name": GROUP}],
            "templates": [
                {
                    "uuid": uid("template", "lab-expiries"),
                    "template": "lab-expiries",
                    "name": "lab-expiries",
                    "description": "Generated by observability/zabbix/build.py from observability/expiries.yaml (ADR 0051). Do not edit.",
                    "groups": [{"name": GROUP}],
                    "items": items,
                }
            ],
        }
    }


def web_ui() -> dict:
    doc = yaml.safe_load((ROOT / "observability" / "observability.yaml").read_text())
    items = []
    for w in doc["web_checks"]:
        key = f"web.status[{w['name']}]"
        insecure = bool(w.get("insecure"))
        items.append(
            {
                "uuid": uid("item", key),
                "name": f"HTTP status: {w['name']} ({w['url']})",
                "type": "HTTP_AGENT",
                "key": key,
                "delay": "1m",
                "value_type": "UNSIGNED",
                "url": w["url"],
                "timeout": "15s",
                "retrieve_mode": "HEADERS",
                "follow_redirects": "NO",
                "verify_peer": "NO" if insecure else "YES",
                "verify_host": "NO" if insecure else "YES",
                "preprocessing": [{"type": "REGEX", "parameters": ["^HTTP/\\S+ (\\d{3})", "\\1"]}],
                "description": "Status code from the response headers." + (" Self-signed certificate: TLS not verified." if insecure else " Verified with the lab CA."),
                "tags": [{"tag": "component", "value": "ui"}, {"tag": "ui", "value": w["name"]}],
                "triggers": [
                    {
                        "uuid": uid("trigger", key),
                        "expression": f"last(/lab-web-ui/{key})<>{w['expect']}",
                        "name": f"LAB: UI {w['name']} answers {{ITEM.LASTVALUE1}} instead of {w['expect']}",
                        "priority": "HIGH",
                        "tags": [{"tag": "scope", "value": "availability"}],
                    }
                ],
            }
        )
    return {
        "zabbix_export": {
            "version": "7.0",
            "template_groups": [{"uuid": uid("group", GROUP), "name": GROUP}],
            "templates": [
                {
                    "uuid": uid("template", "lab-web-ui"),
                    "template": "lab-web-ui",
                    "name": "lab-web-ui",
                    "description": "Generated by observability/zabbix/build.py from observability/observability.yaml web_checks (ADR 0051). Do not edit.",
                    "groups": [{"name": GROUP}],
                    "items": items,
                }
            ],
        }
    }


def main(argv: list[str]) -> int:
    outputs = {"lab-expiries.yaml": _dump(expiries()), "lab-web-ui.yaml": _dump(web_ui())}
    rc = 0
    for name, text in outputs.items():
        path = OUT / name
        if "--check" in argv:
            if not path.exists() or path.read_text() != text:
                print(f"{path} is stale: run observability/zabbix/build.py")
                rc = 1
        else:
            path.write_text(text)
            print(f"wrote {path}")
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
